version: "3.8"
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - "4444:4444"
    volumes:
      - ".:/home/project/api/"
    command: ["./wait-for-postgres.sh", "localhost:5432", "npm", "run", "dev"]
  db:
    image: postgres
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: db123
      POSTGRES_DB: skeleton
volumes:
  dbdata:
