version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: db123
      POSTGRES_DB: skeleton
  api:
    build: .
    depends_on:
      - db
    ports:
      - "4444:4444"
    volumes:
      - ".:/home/project/api/"
volumes:
  dbdata:
