version: "3.8"
services:
  db:
    image: postgres:alpine
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: db123
      POSTGRES_DB: skeleton
volumes:
  dbdata:
